#!/bin/sh
/bin/touch /var/log/messages
case "$1" in
	start|"")
		echo Starting syslogd
		/sbin/syslogd 
		echo Starting klogd
		/sbin/klogd
	;;
	stop)
		echo Stopping syslogd and klogd
		for i in syslogd klogd; do
			if [ -n "$(pidof $i)" ]; then
				kill $(pidof $i);
			else
				echo $i not running!
			fi
		done
	;;
	*)
		echo "Usage: $0 [start|stop]"
		exit 255
	;;
esac

