#!/bin/sh


case "$1" in
	start)
		files=S
	;;
	stop)
		files=K
	;;
	*)
		files=S
		1=start
	;;
esac
		

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/rc.d/$files??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i $1
	    ;;
    esac
done

